name: CI for Windows 7
description: Building xTools for Windows 7

inputs:
  tag:
    description: 'The tag to upload the release asset to.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}'
        modules: 'qtcharts'
    - name: Build for Windows 7
      shell: cmd
      run: |
        git fetch --tags
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/5.15.2/win64_msvc2019_64' -DCMAKE_BUILD_TYPE=Release -DX_VERSION_OVERRIDE:STRING=${{ inputs.tag }} -G "Ninja" ../
        cmake --build . --target all
        cmake --build . --target xTools_zip
    - name: Check for Artifacts
      shell: cmd
      run: |
        for %%f in (bin\5.15.2\Windows\Release\xTools-zip\*.zip) do echo "%%f"
    - name: Upload Release Asset for Windows
      if: ${{ inputs.tag != '' }}
      shell: cmd
      run: |
        for %%f in (bin\5.15.2\Windows\Release\xTools-zip\*.zip) do gh release upload ${{ inputs.tag }} "%%f" --clobber