file(GLOB_RECURSE TOOLS_FILES "${CMAKE_SOURCE_DIR}/src/tools/filemerge/*.*")
file(GLOB_RECURSE X_MERGE_FILES "${CMAKE_CURRENT_LIST_DIR}/src/*.*")
set(PRO_FILES ${CMAKE_CURRENT_LIST_DIR}/xMerge.rc)
list(APPEND PRO_FILES ${CMAKE_CURRENT_LIST_DIR}/xMerge.qrc)
list(APPEND PRO_FILES ${X_COMMON_FILES})
list(APPEND PRO_FILES ${TOOLS_FILES})
list(APPEND PRO_FILES ${X_MERGE_FILES})

include(cmake/x_qt_deploy.cmake)
include(cmake/x_qt_linguist.cmake)
include(cmake/x_3rd_glog.cmake)
include(cmake/msix/msix.cmake)

# --------------------------------------------------------------------------------------------------
include_directories(${CMAKE_SOURCE_DIR}/xapps)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${X_BINS_DIR}/xMerge)
add_compile_definitions(X_NO_NETWORK)
set(x_hash_version "1.0.0")
add_compile_definitions(X_HASH_VERSION="${x_hash_version}")
qt_add_executable(xMerge ${PRO_FILES})
x_deploy_qt(xMerge)
x_using_x_tools_translations(xMerge)
target_link_libraries(xMerge PRIVATE Qt::CorePrivate Qt::Svg Qt::Widgets glog::glog)
if(X_USING_VS_CODE)
  set_target_properties(xMerge PROPERTIES MACOSX_BUNDLE TRUE)
else()
  set_target_properties(xMerge PROPERTIES MACOSX_BUNDLE TRUE WIN32_EXECUTABLE TRUE)
endif()

# --------------------------------------------------------------------------------------------------
if(WIN32)
  target_link_libraries(xMerge PRIVATE Dwmapi)
  x_generate_msix(xMerge "xMerge" "xMerge" "${x_hash_version}" FALSE)
elseif(LINUX)
  target_link_libraries(xMerge PRIVATE dl)
endif()
