name: CI for MacOS
description: Building xTools for MacOS

inputs:
  tag:
    description: 'The tag to upload the release asset to.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Qt for macOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        target: 'desktop'
        arch: 'clang_64'
        dir: ${{ github.workspace }}
        modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
    - name: Build for macOS
      # 278ERROR: no file at "/usr/local/opt/libiodbc/lib/libiodbc.2.dylib"
      # brew unlink unixodbc
      # brew install libiodbc
      # ERROR: no file at "/Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib"
      # ln -s /usr/local/Cellar/postgresql@14/14.10/lib/postgresql@14/libpq.5.14.dylib /Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib
      run: |
        git fetch --tags
        # brew unlink unixodbc
        # brew install libiodbc
        mkdir -p /Applications/Postgres.app/Contents/Versions/14/lib
        ln -s /usr/local/Cellar/postgresql@14/14.10/lib/postgresql@14/libpq.5.14.dylib /Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib
        mkdir build
        cd build
        cmake ../ -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/6.8.3/clang_64/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build . --target all
        cmake --build . --target xTools_dmg
    - name: Upload Release Asset for macOS
      if: ${{ inputs.tag != '' }}
      run: |
        ls bin/6.8.3/Darwin/Release/xTools
        find bin/6.8.3/Darwin/Release/xTools -name "*.dmg" -exec gh release upload ${{ inputs.tag }} {} \;