file(GLOB_RECURSE X_FILES "${CMAKE_SOURCE_DIR}/xapps/x/*.*")
file(GLOB_RECURSE COMMON_FILES "${CMAKE_SOURCE_DIR}/src/common/*.*")
file(GLOB_RECURSE X_HASH_FILES "${CMAKE_CURRENT_LIST_DIR}/src/*.*")
set(PRO_FILES ${CMAKE_CURRENT_LIST_DIR}/xLinguist.rc)
list(APPEND PRO_FILES ${CMAKE_CURRENT_LIST_DIR}/xLinguist.qrc)
list(APPEND PRO_FILES ${X_FILES})
list(APPEND PRO_FILES ${COMMON_FILES})
list(APPEND PRO_FILES ${TOOLS_FILES})
list(APPEND PRO_FILES ${X_HASH_FILES})

include_directories(${CMAKE_SOURCE_DIR}/xapps)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${X_BIN}/xLinguist)
qt_add_executable(xLinguist ${PRO_FILES})
x_deploy_qt(xLinguist)
x_generate_translations(xLinguist)
target_link_libraries(xLinguist PRIVATE Qt6::Core Qt6::Gui Qt6::Svg Qt6::Widgets Qt6::Network)
target_link_libraries(xLinguist PRIVATE Qt6::SerialPort)
if(X_USING_VS_CODE)
  set_target_properties(xLinguist PROPERTIES MACOSX_BUNDLE TRUE)
else()
  set_target_properties(xLinguist PROPERTIES MACOSX_BUNDLE TRUE WIN32_EXECUTABLE TRUE)
endif()

if(WIN32)
  target_link_libraries(xLinguist PRIVATE Dwmapi)
elseif(LINUX)
  target_link_libraries(xLinguist PRIVATE dl)
endif()
