name: CI for Windows XP
description: Building xTools for Windows XP

inputs:
  tag:
    description: 'The tag to upload the release asset to.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Build for Windows XP
      shell: cmd
      run: |
        scripts\ci-build-windows-xp.bat ${{ inputs.tag }}
    - name: Check for Artifacts
      shell: cmd
      run: |
        for %%f in (bin\5.6.3\Windows\Release\xTools-zip\*.zip) do echo "%%f"
    - name: Upload Release Asset for Windows
      if: ${{ inputs.tag != '' }}
      shell: cmd
      run: |
        for %%f in (bin\5.6.3\Windows\Release\xTools-zip\*.zip) do gh release upload ${{ inputs.tag }} "%%f" --clobber