name: CI for Ubuntu ARM
description: Building xTools for Ubuntu ARM

inputs:
  tag:
    description: 'The tag to upload the release asset to.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.3'
        host: 'linux_arm64'
        target: 'desktop'
        arch: 'linux_gcc_arm64'
        modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
        dir: ${{ github.workspace }}

    - name: Install Dependencies
      run: |
        sudo apt-get install -y libxcb-xinerama0 libxcb-cursor-dev libudev-dev libusb-dev libusb-1.0-0-dev ninja-build
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-aarch64.AppImage -O ${{ github.workspace }}/cmake/linux/tools/linuxdeployqt-aarch64
        chmod +x ${{ github.workspace }}/cmake/linux/tools/linuxdeployqt-aarch64
      shell: bash

    - name: Build for Linux ARM
      run: |
        git fetch --tags
        cmake --version
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/6.7.3/linux_gcc_arm64' -DCMAKE_BUILD_TYPE=Release -G "Ninja" ../
        cmake --build . --target xTools
        cmake --build . --target xTools_linux
      shell: bash

    - name: Upload Release Asset for Linux ARM
      if: ${{ inputs.tag != '' }}
      run: |
        dir bin/6.7.3/Linux/Release
        find bin/6.7.3/Linux/Release/xTools-linux -name "*.deb" -exec echo {} \;
        find bin/6.7.3/Linux/Release/xTools-linux -name "*.deb" -exec gh release upload ${{ inputs.tag }} {} \;
        find bin/6.7.3/Linux/Release/xTools-linux -name "*.AppImage" -exec echo  {} \;
        find bin/6.7.3/Linux/Release/xTools-linux -name "*.AppImage" -exec gh release upload ${{ inputs.tag }} {} \;
      shell: bash

