include($$PWD/tcp/SAKTcp.pri)
include($$PWD/udp/SAKUdp.pri)
include($$PWD/debugger/SAKDebugger.pri)
include($$PWD/websocket/SAKWebSocket.pri)
include($$PWD/serialport/SAKSerialPort.pri)
include($$PWD/ble/SAKBluetoothLowEnergy.pri)
include($$PWD/virtualdevice/SAKVirtualDevice.pri)
