macro(x_remove_all_files_of_mqtt)
  message(STATUS "[xTools-xmqtt] Remove all files of xMqtt")
  file(GLOB_RECURSE mqtt_files "${CMAKE_SOURCE_DIR}/src/mqtt/*.*")
  foreach(file ${mqtt_files})
    list(REMOVE_ITEM X_SOURCES ${file})
  endforeach()
endmacro()

if(QT_VERSION VERSION_LESS "6.8.0")
  x_remove_all_files_of_mqtt()
  return()
endif()

option(X_ENABLE_X_MQTT "Enable xMqtt support" ON)
if(NOT X_ENABLE_X_MQTT)
  x_remove_all_files_of_mqtt()
  return()
endif()

include_directories(${CMAKE_SOURCE_DIR}/src/mqtt)
add_compile_definitions(X_ENABLE_X_MQTT)
