macro(x_remove_all_files_of_canbus)
  message(STATUS "[xTools-xcanbus] Remove all files of xCanBus")
  file(GLOB_RECURSE module_files "${CMAKE_SOURCE_DIR}/src/canbus/*.*")
  foreach(file ${module_files})
    list(REMOVE_ITEM X_SOURCES ${file})
  endforeach()
endmacro()

if(QT_VERSION VERSION_LESS "6.8.0")
  x_remove_all_files_of_canbus()
  return()
endif()

option(X_ENABLE_X_CANBUS "Enable xCanBus support" ON)
if(NOT X_ENABLE_X_CANBUS)
  x_remove_all_files_of_mqtt()
  return()
endif()

include_directories(${CMAKE_SOURCE_DIR}/src/canbus)
add_compile_definitions(X_ENABLE_X_CANBUS)
