macro(x_remove_all_files_of_modbus)
  message(STATUS "[xTools-xmodbus] Remove all files of xModbus")
  file(GLOB_RECURSE modbus_files "${CMAKE_SOURCE_DIR}/src/modbus/*.*")
  foreach(file ${modbus_files})
    list(REMOVE_ITEM X_SOURCES ${file})
  endforeach()
endmacro()

if(NOT X_ENABLE_X_APPS)
  x_remove_all_files_of_modbus()
  return()
endif()

if(QT_VERSION VERSION_LESS "6.8.0")
  x_remove_all_files_of_modbus()
  return()
endif()

option(X_ENABLE_X_MODBUS "Enable xModbus support" ON)
if(NOT X_ENABLE_X_MODBUS)
  x_remove_all_files_of_modbus()
  return()
endif()

include_directories(${CMAKE_SOURCE_DIR}/src/modbus)
add_compile_definitions(X_ENABLE_X_MODBUS)
