option(X_ENABLE_X_APPS "Enable xApps" OFF)
add_compile_definitions(X_ENABLE_X_APPS)
include(${CMAKE_CURRENT_LIST_DIR}/x_apps_modbus.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/x_apps_mqtt.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/x_apps_canbus.cmake)
