find_package(Qt${QT_VERSION_MAJOR} QUIET COMPONENTS SerialPort)
set(X_ENABLE_SERIALPORT ${Qt${QT_VERSION_MAJOR}SerialPort_FOUND})

macro(x_remove_x_modem_files)
  add_compile_definitions(X_ENABLE_MODEM=0)
  message(STATUS "Modem module is disable, Modem files will be removed.")
  file(GLOB_RECURSE MODEM_FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/tools/modem/*.*")
  foreach(file ${MODEM_FILES})
    list(REMOVE_ITEM X_SOURCES ${file})
    message(STATUS "[Modem]Remove file: ${file}")
  endforeach()
endmacro()

macro(x_remove_serialport_files)
  add_compile_definitions(X_ENABLE_SERIALPORT=0)
  message(STATUS "SerialPort module is disable, SerialPort files will be removed.")
  file(GLOB_RECURSE SERIAL_PORT_FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/serialport*")
  foreach(file ${SERIAL_PORT_FILES})
    list(REMOVE_ITEM X_SOURCES ${file})
    message(STATUS "[SerialPort]Remove file: ${file}")
  endforeach()
endmacro()

if(X_ENABLE_SERIALPORT)
  add_compile_definitions(X_ENABLE_SERIALPORT=1)
  list(APPEND X_LIBS Qt${QT_VERSION_MAJOR}::SerialPort)

  option(X_ENABLE_MODEM "Enable Modem Assistant" OFF)
  if(X_ENABLE_MODEM)
    if(QT_VERSION VERSION_LESS "6.10.0")
      x_remove_x_modem_files()
    else()
      add_compile_definitions(X_ENABLE_MODEM=1)
    endif()
  else()
    x_remove_x_modem_files()
  endif()
else()
  x_remove_serialport_files()
  x_remove_x_modem_files()
endif()
