macro(x_remove_all_coap_files)
  add_compile_definitions(X_ENABLE_COAP=0)
  return()
endmacro()

option(X_ENABLE_COAP "Enable CoAP support via Qt CoAP module" OFF)
if(NOT X_ENABLE_COAP)
  x_remove_all_coap_files()
  return()
endif()

add_compile_definitions(X_ENABLE_COAP=1)
set(dst_dir ${X_LIBS_DIR}/qtcoap-${QT_VERSION})
if(EXISTS ${dst_dir}/lib/cmake)
  set(Qt6Coap_DIR ${dst_dir}/lib/cmake/Qt6Coap)
  find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Coap)
else()
  x_add_qt_module(qtcoap)
endif()
list(APPEND X_LIBS Qt6::Coap)
