macro(x_remove_all_http_files)
  add_compile_definitions(X_ENABLE_X_HTTP=0)
  file(GLOB_RECURSE http_files ${CMAKE_SOURCE_DIR}/src/x/http/*.*)
  foreach(file_path ${http_files})
    message(STATUS "[xTools.Http]Removing HTTP file: ${file_path}")
    list(REMOVE_ITEM X_SOURCES ${file_path})
  endforeach()
endmacro()

if(ANDROID OR IOS)
  x_remove_all_http_files()
  return()
endif()

if(NOT WIN32)
  x_remove_all_http_files()
  return()
endif()

option(X_ENABLE_X_HTTP "Enable HTTP support via libhttp" OFF)
if(NOT X_ENABLE_X_HTTP)
  x_remove_all_http_files()
  return()
endif()
