/***************************************************************************************************
 * Copyright 2025-2026 x-tools-author(x-tools@outlook.com). All rights reserved.
 *
 * The file is encoded using "utf8 with bom", it is a part of eTools project.
 *
 * eTools is licensed according to the terms in the file LICENCE(GPL V3) in the root of the source
 * code directory.
 **************************************************************************************************/
#include "panel.h"

Panel::Panel(QWidget *parent)
    : QWidget(parent)
{}

Panel::~Panel() {}

QVariantMap Panel::save() const
{
    return QVariantMap();
}

/**
 * @brief Panel::load Load panel parameters
 * @param parameters Panel parameters, which is generated by Panel::save() before
 */
void Panel::load(const QVariantMap &parameters)
{
    Q_UNUSED(parameters);
}

/**
 * @brief Panel::onBytesRead Called when bytes are read from the device.
 * @param bytes The bytes read from the device
 * @param flag The data flag, such as: com3, com4, 192.168.1.168:8080, etc.
 */
void Panel::onBytesRead(const QByteArray &bytes, const QString &flag)
{
    Q_UNUSED(bytes);
    Q_UNUSED(flag);
}

/**
 * @brief Panel::onBytesWritten Called when bytes are written to the device.
 * @param bytes The bytes written to the device
 * @param flag The data flag, such as: com3, com4,
 */
void Panel::onBytesWritten(const QByteArray &bytes, const QString &flag)
{
    Q_UNUSED(bytes);
    Q_UNUSED(flag);
}