name: build-test
on:
  schedule:
    - cron: "0 4 * * 6"
  workflow_dispatch: # Enables manually
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  # push:
  #   branches:
  #     - master
jobs:
  build-windows:
    name: Qt5(windows)
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 5.15.2
            arch: win64_msvc2019_64
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: list-dir
        shell: cmd
        run: |
          dir "C:\Program Files"
          dir "${{ github.workspace }}\Qt\${{ matrix.version }}"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "Ninja" ../
          cmake --build . --target all --config Release
