name: build-windows-mingw
on:
  push
  
jobs:
  build-test:
    name: Build the project for windows platform with Qt5 and mingw
    runs-on: windows-2019
    strategy:
      matrix:
        qt_ver: [5.12.10, 5.15.2]
        qt_target: [desktop]
        include:
          - qt_ver: 5.12.10
            qt_arch: win64_mingw73
            qt_arch_install: mingw73_64
          - qt_ver: 5.15.2
            qt_arch: win64_mingw81
            qt_arch_install: mingw81_64
    steps:
      # Cache Qt
      - name: cacheQt
        id: WindowsCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch_install}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cached: ${{steps.WindowsCacheQt.outputs.cache-hit }}
      # Pull code and checkout.
      - name: Pull code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # Build the project
      - name: build-mingw
        shell: cmd
        run: |
          qmake
          make
